/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionSection: typeof import('./components/ActionSection.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LandingHero: typeof import('./components/LandingHero.vue')['default']
    MainLayout: typeof import('./components/MainLayout.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    OrderSection: typeof import('./components/OrderSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceSection: typeof import('./components/ServiceSection.vue')['default']
    TextSection: typeof import('./components/TextSection.vue')['default']
  }
}
